logging:
  level:
    com.github.devgcoder: DEBUG
  pattern:
    file: '%date{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    console: '%date{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  file:
    max-history: 7
    name: ./logs/demo.log


devg:
  monitor:
    queue-type: rabbitmq
    monitor-name: 监控系统
    model-name: monitor
    local-port: 8080
    evn-name: dev
    authorized-user: admin,123456
    messageMaxCostTime: 3000
    messageError: true
    messageOvertime: true
    rabbit-config:
      rabbit-host: 127.0.0.1
      rabbit-port: 5672
      rabbit-username: rabbitadmin
      rabbit-password: 123456
      rabbit-virtual-host: dev
      rabbit-thread-pool-size: 30
      rabbit-monitor-message:
        exchange-name: monitor_exchange
        queue-name: monitor_message_consumer
        route-key: monitor_message_consumer
    elasticSearchConfig:
      hostname: 47.111.253.191
      port: 9201
      schemeName: http
      connectionTimeOut: 30000
      socketTimeOut: 30000
      connectionRequestTimeOut: 30000
      maxConnectTotal: 60
      maxConnectPerRoute: 20
    #    dingdingConfig:
    #      serverUrl: http://www.xxxxxx.com:8090/dingDing/robotMsg
    #      isAtAll: false
    monitorNonClassMethod:
    - com.fasterxml.jackson.databind.ObjectMapper
    - com.github.devgcoder.monitor.web.controller.MonitorIndexController